### ISSUE TITLE
path-to-regexp

### ISSUE THREAD

**Issue by jonathanong** [pillarjs/discussions#3]
https://github.com/jshttp/jshttp.github.io/issues/23
https://github.com/jshttp/jshttp.github.io/issues/17

**Comment by jonathanong** [comment]
going to move `path-match`. any objections?

**Comment by dougwilson** [comment]
oh, i thought this couldn't be moved because of components or something?

**Comment by jonathanong** [comment]
whatever haha duo is out so people can use that
