### ISSUE TITLE
trie router

### ISSUE THREAD

**Issue by jonathanong** [pillarjs/discussions#6]
like path-to-regexp, but with trie routing instead: https://github.com/jonathanong/routington

like to move it in here :D

**Comment by yoshuawuyts** [comment]
+1, trie routing is beautiful! :D

**Comment by dougwilson** [comment]
yea, that's what i eventually want to bring the `router` module to be: a real router by URL and stuff, not a stack of functions (though a function stack is probably still useful i guess, so it would eventually just be it's own module)

**Comment by jonathanong** [comment]
i dunno... i think the main router should remain regexp and a stack of functions. it's more flexible. i found trie routing a little too strict and only use it with routes that have more than 2 fragments, i.e. `/a/b/...`

**Comment by dougwilson** [comment]
> a little too strict 

right. what i see is like a combination of the two. the way the router in Mojolicious is designed is good and combines both approaches and scales well for string paths

**Comment by jonathanong** [comment]
i moved it :) if you guys want to rename it to something better, open a new issue in the repo!
