### ISSUE TITLE
Settings stuff

### ISSUE THREAD

**Issue by Fishrock123** [pillarjs/discussions#7]
Basically ported express stuff that will be built in for now but that no-one will have to even include.

@dougwilson What's the progress on this? I'm not so sure how this will all work, but if I have an idea I can get working on the docs.

**Comment by dougwilson** [comment]
i'm going to cc @thomasfr here, as he may be interested in our conversation around this :)

**Comment by jonathanong** [comment]
meh. i personally dislike settings systems in frameworks. settings should be minimal, but i guess it's required for backwards compat

**Comment by dougwilson** [comment]
right. idk, in the end. i was thinking of a bag-o-things with get/set, but yes, in the end this would be for express back-compat only, so we can probably drop this anyway (especially since i didn't get any traction from people asking for module names)

**Comment by Fishrock123** [comment]
@dougwilson so maybe just keep this stuff in pillar 1.0 for now and just remove it for v2?

**Comment by dougwilson** [comment]
right, we can just keep the setting in the glue lib itself, rather than other for now.

**Comment by Fishrock123** [comment]
Hmmm, I'm not 100% sure, by the glue lib do you mean pillar or a glue module?

**Comment by dougwilson** [comment]
yes, "pillar" -- the things that'll glue everything together into an "express"
