### ISSUE TITLE
csrf

### ISSUE THREAD

**Issue by jonathanong** [pillarjs/discussions#8]
https://github.com/jshttp/jshttp.github.io/issues/13

**Comment by jonathanong** [comment]
@dougwilson anything you wanted to change with `csrf-tokens`? otherwise i'm gonna move it here and rename it to `csrf`

**Comment by dougwilson** [comment]
it would be nice to pin the deps (at least a bit more than `"1"`?), but otherwise fine. I like the new name, because if you look at csurf, it doesn't do much but wrap the token and make it express-friendly, which is how the pillarjs modules should be :)

**Comment by jonathanong** [comment]
done :D
