### ISSUE TITLE
ssl-redirect

### ISSUE THREAD

**Issue by jonathanong** [pillarjs/discussions#9]
https://github.com/expressjs/ssl-redirect

aye or naye? might be useful in frameworks when users want ssl only.

**Comment by dougwilson** [comment]
yea. i also have a http+https wrapper i made a while ago that is similar. seems useful, though i'd like to clean it before moving (lol; i'm trying to just clean up the modules before dumping so the orgs don't turn into a dumping ground or something, haha).

**Comment by Fishrock123** [comment]
Seems a little more complex than it needs to be?

[What I'm using right now..](https://github.com/Fishrock123/Searchbeam/blob/master/app.js#L140-L148)

**Comment by jonathanong** [comment]
yeah it be more useful, maybe never even bother sending a JSON response.

**Comment by jonathanong** [comment]
@dougwilson did you have anything specific to change? or did you just want to do it yourself later?

**Comment by Fishrock123** [comment]
If it gets moved I'm gona do some simplification on it so that I'll want to use it myself haha.

Also, I'll double check, but I'm 90% sure I'll be stripping the Cache-Control thing as per the comment.

**Comment by jonathanong** [comment]
k moved. feel free to make simplifications or whatever. i'll wait a while to release a v1.
